# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
    name: vmss_pool    

stages:
  - stage:
    jobs:
    # Define the first job
    - job: Job1
      displayName: Job 1
      steps:
      - script: echo "Running Job 1"

    # Define the second job (runs in parallel to Job 1)
    - job: Job2
      displayName: Job 2
      steps:
      - script: echo "Running Job 2"

    # Define the third job (runs in parallel to Job 1 and Job 2)
    - job: Job3
      displayName: Job 3
      steps:
      - script: echo "Running Job 3"